ALTER TABLE [t_ICD-10_ICD-9_with_GEM_AXIS] ALTER COLUMN [DX_CAT] varchar(8) NULL
UPDATE [t_ICD-10_ICD-9_with_GEM_AXIS]
SET [t_ICD-10_ICD-9_with_GEM_AXIS].[DX_CAT] = [t_ICD-10_ICD-10_with_GEM_AXIS].DX_CAT
FROM [t_ICD-10_ICD-10_with_GEM_AXIS] INNER JOIN
[t_ICD-10_ICD-9_with_GEM_AXIS] ON [t_ICD-10_ICD-10_with_GEM_AXIS].[ICD-10_Code] = [t_ICD-10_ICD-9_with_GEM_AXIS].[ICD-10_Code]
